#!/usr/bin/env bash

remoteIP="devops.us.priv.hyperspire.net"
netName="HyperNet"

red='\e[31m\e[1m'
green='\e[32m\e[1m'
background='\e[40m'
normal='\e[0m'

# function getNetworkStatus () {
#   [[ -n $(ping $remoteIP -c 1 -W 1 | grep '100%') ]] && printf "${red}⬢${normal} ${background}[ ${red}Warning${normal}${background}: $netName is offline. ]$normal" || printf "${green}⬢${normal} ${background}[ Liberty Prime: ${green}ONLINE${normal}${background} - Voice Module: ${green}ACTIVE${normal}${background} - Weapons: ${red}HOT${normal}${background} ]$normal"
# }

function getNetworkStatus () {
  while [[ $? ]]; do
    [[ -n $(ping $remoteIP -c 1 -W 1 | grep '100%') ]] && network_down=true
    if [[ $network_down ]]; then
      printf "${red}⬢${normal} ${background}[ ${red}Warning${normal}${background}: $netName is offline - $(sudo service devops-server status 2> /dev/null | sed -n \$p) ]$normal"
      unset network_down
      sleep 150
    else
      printf "${green}⬢${normal} ${background}[ Liberty Prime: ${green}ONLINE${normal}${background} - Voice Module: ${green}ACTIVE${normal}${background} - Weapons: ${red}HOT${normal}${background} ]$normal"
      sleep 150
    fi
  done
}

getNetworkStatus
