#!/usr/bin/env bash

remoteIP="10.10.10.10"
netName="HyperNet"

red='\e[31m\e[1m'
green='\e[32m\e[1m'
background='\e[40m'
normal='\e[0m'

function getNetworkStatus () {
  [[ -n $(ping $remoteIP -c 1 -W 1 | grep '100%') ]] && printf "$red⬢$normal [ $redWarning$normal: $netName is offline. ] " || printf "$green⬢$normal $background[ Liberty Prime: ${green}ONLINE${normal}${background} - Voice Module: ${green}ACTIVE${normal}${background} - Weapons: ${red}HOT${normal}${background} ]$normal"
}

getNetworkStatus
